name: CI

on: [push, pull_request]

env:
  CI: true
  DOCKER_AUTH: ${{ secrets.DOCKER_AUTH }}

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: Build image
      run: docker build -t karimsa/watchtower .
    - name: docker login
      if: github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/v')
      run: |
        mkdir -p ~/.docker
        echo "{\"auths\":{\"https://index.docker.io/v1/\":{\"auth\":\"$DOCKER_AUTH\"}}}" > ~/.docker/config.json
    - name: docker push karimsa/watchtower:unstable
      if: github.ref == 'refs/heads/master'
      run: |
        docker tag karimsa/watchtower karimsa/watchtower:unstable
        docker push karimsa/watchtower:unstable
    - uses: meeDamian/sync-readme@v1.0.6
      if: startsWith(github.ref, 'refs/tags/v')
      with:
        user: karimsa
        pass: ${{ secrets.DOCKER_PASS }}
        slug: karimsa/watchtower
        readme: README.md
    - if: startsWith(github.ref, 'refs/tags/v')
      run: |
        set -ex
        docker tag karimsa/watchtower karimsa/watchtower:${GITHUB_REF#*/*/v}
        docker push karimsa/watchtower:latest
